version: '3.2'

services:

  api:
    build:
      context: ../../
      dockerfile: local/docker/fastapi/Dockerfile
    container_name: hf_api
    working_dir: /code/app
    ports:
      - 127.0.0.1:8580:8080
    volumes:
      - ${PWD}/app:/code/app/app
